# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danieljob/Escritorio/FortuneAvenueDev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danieljob/Escritorio/FortuneAvenueDev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danieljob/Escritorio/FortuneAvenueDev/CMakeFiles /home/danieljob/Escritorio/FortuneAvenueDev//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danieljob/Escritorio/FortuneAvenueDev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fortuneAvenue

# Build rule for target.
fortuneAvenue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fortuneAvenue
.PHONY : fortuneAvenue

# fast build rule for target.
fortuneAvenue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/build
.PHONY : fortuneAvenue/fast

FortuneAvenueDev/src/cinematic/Cinematic.o: FortuneAvenueDev/src/cinematic/Cinematic.cpp.o
.PHONY : FortuneAvenueDev/src/cinematic/Cinematic.o

# target to build an object file
FortuneAvenueDev/src/cinematic/Cinematic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/cinematic/Cinematic.cpp.o
.PHONY : FortuneAvenueDev/src/cinematic/Cinematic.cpp.o

FortuneAvenueDev/src/cinematic/Cinematic.i: FortuneAvenueDev/src/cinematic/Cinematic.cpp.i
.PHONY : FortuneAvenueDev/src/cinematic/Cinematic.i

# target to preprocess a source file
FortuneAvenueDev/src/cinematic/Cinematic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/cinematic/Cinematic.cpp.i
.PHONY : FortuneAvenueDev/src/cinematic/Cinematic.cpp.i

FortuneAvenueDev/src/cinematic/Cinematic.s: FortuneAvenueDev/src/cinematic/Cinematic.cpp.s
.PHONY : FortuneAvenueDev/src/cinematic/Cinematic.s

# target to generate assembly for a file
FortuneAvenueDev/src/cinematic/Cinematic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/cinematic/Cinematic.cpp.s
.PHONY : FortuneAvenueDev/src/cinematic/Cinematic.cpp.s

FortuneAvenueDev/src/core/ObjetosGlobal.o: FortuneAvenueDev/src/core/ObjetosGlobal.cpp.o
.PHONY : FortuneAvenueDev/src/core/ObjetosGlobal.o

# target to build an object file
FortuneAvenueDev/src/core/ObjetosGlobal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/core/ObjetosGlobal.cpp.o
.PHONY : FortuneAvenueDev/src/core/ObjetosGlobal.cpp.o

FortuneAvenueDev/src/core/ObjetosGlobal.i: FortuneAvenueDev/src/core/ObjetosGlobal.cpp.i
.PHONY : FortuneAvenueDev/src/core/ObjetosGlobal.i

# target to preprocess a source file
FortuneAvenueDev/src/core/ObjetosGlobal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/core/ObjetosGlobal.cpp.i
.PHONY : FortuneAvenueDev/src/core/ObjetosGlobal.cpp.i

FortuneAvenueDev/src/core/ObjetosGlobal.s: FortuneAvenueDev/src/core/ObjetosGlobal.cpp.s
.PHONY : FortuneAvenueDev/src/core/ObjetosGlobal.s

# target to generate assembly for a file
FortuneAvenueDev/src/core/ObjetosGlobal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/core/ObjetosGlobal.cpp.s
.PHONY : FortuneAvenueDev/src/core/ObjetosGlobal.cpp.s

FortuneAvenueDev/src/core/ResourceGlobal.o: FortuneAvenueDev/src/core/ResourceGlobal.cpp.o
.PHONY : FortuneAvenueDev/src/core/ResourceGlobal.o

# target to build an object file
FortuneAvenueDev/src/core/ResourceGlobal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/core/ResourceGlobal.cpp.o
.PHONY : FortuneAvenueDev/src/core/ResourceGlobal.cpp.o

FortuneAvenueDev/src/core/ResourceGlobal.i: FortuneAvenueDev/src/core/ResourceGlobal.cpp.i
.PHONY : FortuneAvenueDev/src/core/ResourceGlobal.i

# target to preprocess a source file
FortuneAvenueDev/src/core/ResourceGlobal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/core/ResourceGlobal.cpp.i
.PHONY : FortuneAvenueDev/src/core/ResourceGlobal.cpp.i

FortuneAvenueDev/src/core/ResourceGlobal.s: FortuneAvenueDev/src/core/ResourceGlobal.cpp.s
.PHONY : FortuneAvenueDev/src/core/ResourceGlobal.s

# target to generate assembly for a file
FortuneAvenueDev/src/core/ResourceGlobal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/core/ResourceGlobal.cpp.s
.PHONY : FortuneAvenueDev/src/core/ResourceGlobal.cpp.s

FortuneAvenueDev/src/game/offiline/Bot.o: FortuneAvenueDev/src/game/offiline/Bot.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/Bot.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/Bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/Bot.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/Bot.cpp.o

FortuneAvenueDev/src/game/offiline/Bot.i: FortuneAvenueDev/src/game/offiline/Bot.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/Bot.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/Bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/Bot.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/Bot.cpp.i

FortuneAvenueDev/src/game/offiline/Bot.s: FortuneAvenueDev/src/game/offiline/Bot.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/Bot.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/Bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/Bot.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/Bot.cpp.s

FortuneAvenueDev/src/game/offiline/GameEndO.o: FortuneAvenueDev/src/game/offiline/GameEndO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameEndO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/GameEndO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameEndO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameEndO.cpp.o

FortuneAvenueDev/src/game/offiline/GameEndO.i: FortuneAvenueDev/src/game/offiline/GameEndO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameEndO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/GameEndO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameEndO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameEndO.cpp.i

FortuneAvenueDev/src/game/offiline/GameEndO.s: FortuneAvenueDev/src/game/offiline/GameEndO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameEndO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/GameEndO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameEndO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameEndO.cpp.s

FortuneAvenueDev/src/game/offiline/GameManager.o: FortuneAvenueDev/src/game/offiline/GameManager.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameManager.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/GameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameManager.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameManager.cpp.o

FortuneAvenueDev/src/game/offiline/GameManager.i: FortuneAvenueDev/src/game/offiline/GameManager.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameManager.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameManager.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameManager.cpp.i

FortuneAvenueDev/src/game/offiline/GameManager.s: FortuneAvenueDev/src/game/offiline/GameManager.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameManager.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameManager.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameManager.cpp.s

FortuneAvenueDev/src/game/offiline/GameOfflineO.o: FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameOfflineO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.o

FortuneAvenueDev/src/game/offiline/GameOfflineO.i: FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameOfflineO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.i

FortuneAvenueDev/src/game/offiline/GameOfflineO.s: FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameOfflineO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameOfflineO.cpp.s

FortuneAvenueDev/src/game/offiline/GameOptionsO.o: FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameOptionsO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.o

FortuneAvenueDev/src/game/offiline/GameOptionsO.i: FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameOptionsO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.i

FortuneAvenueDev/src/game/offiline/GameOptionsO.s: FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameOptionsO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/GameOptionsO.cpp.s

FortuneAvenueDev/src/game/offiline/HouseBuyO.o: FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/HouseBuyO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.o

FortuneAvenueDev/src/game/offiline/HouseBuyO.i: FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/HouseBuyO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.i

FortuneAvenueDev/src/game/offiline/HouseBuyO.s: FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/HouseBuyO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/HouseBuyO.cpp.s

FortuneAvenueDev/src/game/offiline/MovePiecesO.o: FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/MovePiecesO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.o

FortuneAvenueDev/src/game/offiline/MovePiecesO.i: FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/MovePiecesO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.i

FortuneAvenueDev/src/game/offiline/MovePiecesO.s: FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/MovePiecesO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/MovePiecesO.cpp.s

FortuneAvenueDev/src/game/offiline/PieceSelectorO.o: FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/PieceSelectorO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.o

FortuneAvenueDev/src/game/offiline/PieceSelectorO.i: FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/PieceSelectorO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.i

FortuneAvenueDev/src/game/offiline/PieceSelectorO.s: FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/PieceSelectorO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/PieceSelectorO.cpp.s

FortuneAvenueDev/src/game/offiline/ResourceGameO.o: FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/ResourceGameO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.o

FortuneAvenueDev/src/game/offiline/ResourceGameO.i: FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/ResourceGameO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.i

FortuneAvenueDev/src/game/offiline/ResourceGameO.s: FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/ResourceGameO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/ResourceGameO.cpp.s

FortuneAvenueDev/src/game/offiline/RuletaO.o: FortuneAvenueDev/src/game/offiline/RuletaO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/RuletaO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/RuletaO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/RuletaO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/RuletaO.cpp.o

FortuneAvenueDev/src/game/offiline/RuletaO.i: FortuneAvenueDev/src/game/offiline/RuletaO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/RuletaO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/RuletaO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/RuletaO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/RuletaO.cpp.i

FortuneAvenueDev/src/game/offiline/RuletaO.s: FortuneAvenueDev/src/game/offiline/RuletaO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/RuletaO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/RuletaO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/RuletaO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/RuletaO.cpp.s

FortuneAvenueDev/src/game/offiline/StealplayerO.o: FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/StealplayerO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.o

FortuneAvenueDev/src/game/offiline/StealplayerO.i: FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/StealplayerO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.i

FortuneAvenueDev/src/game/offiline/StealplayerO.s: FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/StealplayerO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/StealplayerO.cpp.s

FortuneAvenueDev/src/game/offiline/nuloO.o: FortuneAvenueDev/src/game/offiline/nuloO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/nuloO.o

# target to build an object file
FortuneAvenueDev/src/game/offiline/nuloO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/nuloO.cpp.o
.PHONY : FortuneAvenueDev/src/game/offiline/nuloO.cpp.o

FortuneAvenueDev/src/game/offiline/nuloO.i: FortuneAvenueDev/src/game/offiline/nuloO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/nuloO.i

# target to preprocess a source file
FortuneAvenueDev/src/game/offiline/nuloO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/nuloO.cpp.i
.PHONY : FortuneAvenueDev/src/game/offiline/nuloO.cpp.i

FortuneAvenueDev/src/game/offiline/nuloO.s: FortuneAvenueDev/src/game/offiline/nuloO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/nuloO.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/offiline/nuloO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/offiline/nuloO.cpp.s
.PHONY : FortuneAvenueDev/src/game/offiline/nuloO.cpp.s

FortuneAvenueDev/src/game/online/Chat.o: FortuneAvenueDev/src/game/online/Chat.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/Chat.o

# target to build an object file
FortuneAvenueDev/src/game/online/Chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Chat.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/Chat.cpp.o

FortuneAvenueDev/src/game/online/Chat.i: FortuneAvenueDev/src/game/online/Chat.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/Chat.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/Chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Chat.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/Chat.cpp.i

FortuneAvenueDev/src/game/online/Chat.s: FortuneAvenueDev/src/game/online/Chat.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/Chat.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/Chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Chat.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/Chat.cpp.s

FortuneAvenueDev/src/game/online/GameEnd.o: FortuneAvenueDev/src/game/online/GameEnd.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/GameEnd.o

# target to build an object file
FortuneAvenueDev/src/game/online/GameEnd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/GameEnd.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/GameEnd.cpp.o

FortuneAvenueDev/src/game/online/GameEnd.i: FortuneAvenueDev/src/game/online/GameEnd.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/GameEnd.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/GameEnd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/GameEnd.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/GameEnd.cpp.i

FortuneAvenueDev/src/game/online/GameEnd.s: FortuneAvenueDev/src/game/online/GameEnd.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/GameEnd.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/GameEnd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/GameEnd.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/GameEnd.cpp.s

FortuneAvenueDev/src/game/online/HouseBuy.o: FortuneAvenueDev/src/game/online/HouseBuy.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/HouseBuy.o

# target to build an object file
FortuneAvenueDev/src/game/online/HouseBuy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/HouseBuy.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/HouseBuy.cpp.o

FortuneAvenueDev/src/game/online/HouseBuy.i: FortuneAvenueDev/src/game/online/HouseBuy.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/HouseBuy.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/HouseBuy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/HouseBuy.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/HouseBuy.cpp.i

FortuneAvenueDev/src/game/online/HouseBuy.s: FortuneAvenueDev/src/game/online/HouseBuy.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/HouseBuy.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/HouseBuy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/HouseBuy.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/HouseBuy.cpp.s

FortuneAvenueDev/src/game/online/MovePieces.o: FortuneAvenueDev/src/game/online/MovePieces.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/MovePieces.o

# target to build an object file
FortuneAvenueDev/src/game/online/MovePieces.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/MovePieces.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/MovePieces.cpp.o

FortuneAvenueDev/src/game/online/MovePieces.i: FortuneAvenueDev/src/game/online/MovePieces.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/MovePieces.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/MovePieces.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/MovePieces.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/MovePieces.cpp.i

FortuneAvenueDev/src/game/online/MovePieces.s: FortuneAvenueDev/src/game/online/MovePieces.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/MovePieces.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/MovePieces.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/MovePieces.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/MovePieces.cpp.s

FortuneAvenueDev/src/game/online/MultiplayerGame.o: FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/MultiplayerGame.o

# target to build an object file
FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.o

FortuneAvenueDev/src/game/online/MultiplayerGame.i: FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/MultiplayerGame.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.i

FortuneAvenueDev/src/game/online/MultiplayerGame.s: FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/MultiplayerGame.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/MultiplayerGame.cpp.s

FortuneAvenueDev/src/game/online/OnlineVars.o: FortuneAvenueDev/src/game/online/OnlineVars.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/OnlineVars.o

# target to build an object file
FortuneAvenueDev/src/game/online/OnlineVars.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/OnlineVars.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/OnlineVars.cpp.o

FortuneAvenueDev/src/game/online/OnlineVars.i: FortuneAvenueDev/src/game/online/OnlineVars.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/OnlineVars.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/OnlineVars.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/OnlineVars.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/OnlineVars.cpp.i

FortuneAvenueDev/src/game/online/OnlineVars.s: FortuneAvenueDev/src/game/online/OnlineVars.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/OnlineVars.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/OnlineVars.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/OnlineVars.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/OnlineVars.cpp.s

FortuneAvenueDev/src/game/online/PieceSelector.o: FortuneAvenueDev/src/game/online/PieceSelector.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/PieceSelector.o

# target to build an object file
FortuneAvenueDev/src/game/online/PieceSelector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/PieceSelector.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/PieceSelector.cpp.o

FortuneAvenueDev/src/game/online/PieceSelector.i: FortuneAvenueDev/src/game/online/PieceSelector.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/PieceSelector.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/PieceSelector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/PieceSelector.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/PieceSelector.cpp.i

FortuneAvenueDev/src/game/online/PieceSelector.s: FortuneAvenueDev/src/game/online/PieceSelector.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/PieceSelector.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/PieceSelector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/PieceSelector.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/PieceSelector.cpp.s

FortuneAvenueDev/src/game/online/ResourceGame.o: FortuneAvenueDev/src/game/online/ResourceGame.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/ResourceGame.o

# target to build an object file
FortuneAvenueDev/src/game/online/ResourceGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/ResourceGame.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/ResourceGame.cpp.o

FortuneAvenueDev/src/game/online/ResourceGame.i: FortuneAvenueDev/src/game/online/ResourceGame.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/ResourceGame.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/ResourceGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/ResourceGame.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/ResourceGame.cpp.i

FortuneAvenueDev/src/game/online/ResourceGame.s: FortuneAvenueDev/src/game/online/ResourceGame.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/ResourceGame.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/ResourceGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/ResourceGame.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/ResourceGame.cpp.s

FortuneAvenueDev/src/game/online/Ruleta.o: FortuneAvenueDev/src/game/online/Ruleta.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/Ruleta.o

# target to build an object file
FortuneAvenueDev/src/game/online/Ruleta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Ruleta.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/Ruleta.cpp.o

FortuneAvenueDev/src/game/online/Ruleta.i: FortuneAvenueDev/src/game/online/Ruleta.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/Ruleta.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/Ruleta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Ruleta.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/Ruleta.cpp.i

FortuneAvenueDev/src/game/online/Ruleta.s: FortuneAvenueDev/src/game/online/Ruleta.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/Ruleta.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/Ruleta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Ruleta.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/Ruleta.cpp.s

FortuneAvenueDev/src/game/online/Stealplayer.o: FortuneAvenueDev/src/game/online/Stealplayer.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/Stealplayer.o

# target to build an object file
FortuneAvenueDev/src/game/online/Stealplayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Stealplayer.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/Stealplayer.cpp.o

FortuneAvenueDev/src/game/online/Stealplayer.i: FortuneAvenueDev/src/game/online/Stealplayer.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/Stealplayer.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/Stealplayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Stealplayer.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/Stealplayer.cpp.i

FortuneAvenueDev/src/game/online/Stealplayer.s: FortuneAvenueDev/src/game/online/Stealplayer.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/Stealplayer.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/Stealplayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/Stealplayer.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/Stealplayer.cpp.s

FortuneAvenueDev/src/game/online/loading.o: FortuneAvenueDev/src/game/online/loading.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/loading.o

# target to build an object file
FortuneAvenueDev/src/game/online/loading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/loading.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/loading.cpp.o

FortuneAvenueDev/src/game/online/loading.i: FortuneAvenueDev/src/game/online/loading.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/loading.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/loading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/loading.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/loading.cpp.i

FortuneAvenueDev/src/game/online/loading.s: FortuneAvenueDev/src/game/online/loading.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/loading.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/loading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/loading.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/loading.cpp.s

FortuneAvenueDev/src/game/online/nulo.o: FortuneAvenueDev/src/game/online/nulo.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/nulo.o

# target to build an object file
FortuneAvenueDev/src/game/online/nulo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/nulo.cpp.o
.PHONY : FortuneAvenueDev/src/game/online/nulo.cpp.o

FortuneAvenueDev/src/game/online/nulo.i: FortuneAvenueDev/src/game/online/nulo.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/nulo.i

# target to preprocess a source file
FortuneAvenueDev/src/game/online/nulo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/nulo.cpp.i
.PHONY : FortuneAvenueDev/src/game/online/nulo.cpp.i

FortuneAvenueDev/src/game/online/nulo.s: FortuneAvenueDev/src/game/online/nulo.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/nulo.s

# target to generate assembly for a file
FortuneAvenueDev/src/game/online/nulo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/game/online/nulo.cpp.s
.PHONY : FortuneAvenueDev/src/game/online/nulo.cpp.s

FortuneAvenueDev/src/main.o: FortuneAvenueDev/src/main.cpp.o
.PHONY : FortuneAvenueDev/src/main.o

# target to build an object file
FortuneAvenueDev/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/main.cpp.o
.PHONY : FortuneAvenueDev/src/main.cpp.o

FortuneAvenueDev/src/main.i: FortuneAvenueDev/src/main.cpp.i
.PHONY : FortuneAvenueDev/src/main.i

# target to preprocess a source file
FortuneAvenueDev/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/main.cpp.i
.PHONY : FortuneAvenueDev/src/main.cpp.i

FortuneAvenueDev/src/main.s: FortuneAvenueDev/src/main.cpp.s
.PHONY : FortuneAvenueDev/src/main.s

# target to generate assembly for a file
FortuneAvenueDev/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/main.cpp.s
.PHONY : FortuneAvenueDev/src/main.cpp.s

FortuneAvenueDev/src/menu/GameModeSelector.o: FortuneAvenueDev/src/menu/GameModeSelector.cpp.o
.PHONY : FortuneAvenueDev/src/menu/GameModeSelector.o

# target to build an object file
FortuneAvenueDev/src/menu/GameModeSelector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/GameModeSelector.cpp.o
.PHONY : FortuneAvenueDev/src/menu/GameModeSelector.cpp.o

FortuneAvenueDev/src/menu/GameModeSelector.i: FortuneAvenueDev/src/menu/GameModeSelector.cpp.i
.PHONY : FortuneAvenueDev/src/menu/GameModeSelector.i

# target to preprocess a source file
FortuneAvenueDev/src/menu/GameModeSelector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/GameModeSelector.cpp.i
.PHONY : FortuneAvenueDev/src/menu/GameModeSelector.cpp.i

FortuneAvenueDev/src/menu/GameModeSelector.s: FortuneAvenueDev/src/menu/GameModeSelector.cpp.s
.PHONY : FortuneAvenueDev/src/menu/GameModeSelector.s

# target to generate assembly for a file
FortuneAvenueDev/src/menu/GameModeSelector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/GameModeSelector.cpp.s
.PHONY : FortuneAvenueDev/src/menu/GameModeSelector.cpp.s

FortuneAvenueDev/src/menu/IniciaUser.o: FortuneAvenueDev/src/menu/IniciaUser.cpp.o
.PHONY : FortuneAvenueDev/src/menu/IniciaUser.o

# target to build an object file
FortuneAvenueDev/src/menu/IniciaUser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/IniciaUser.cpp.o
.PHONY : FortuneAvenueDev/src/menu/IniciaUser.cpp.o

FortuneAvenueDev/src/menu/IniciaUser.i: FortuneAvenueDev/src/menu/IniciaUser.cpp.i
.PHONY : FortuneAvenueDev/src/menu/IniciaUser.i

# target to preprocess a source file
FortuneAvenueDev/src/menu/IniciaUser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/IniciaUser.cpp.i
.PHONY : FortuneAvenueDev/src/menu/IniciaUser.cpp.i

FortuneAvenueDev/src/menu/IniciaUser.s: FortuneAvenueDev/src/menu/IniciaUser.cpp.s
.PHONY : FortuneAvenueDev/src/menu/IniciaUser.s

# target to generate assembly for a file
FortuneAvenueDev/src/menu/IniciaUser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/IniciaUser.cpp.s
.PHONY : FortuneAvenueDev/src/menu/IniciaUser.cpp.s

FortuneAvenueDev/src/menu/IniciarPartida.o: FortuneAvenueDev/src/menu/IniciarPartida.cpp.o
.PHONY : FortuneAvenueDev/src/menu/IniciarPartida.o

# target to build an object file
FortuneAvenueDev/src/menu/IniciarPartida.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/IniciarPartida.cpp.o
.PHONY : FortuneAvenueDev/src/menu/IniciarPartida.cpp.o

FortuneAvenueDev/src/menu/IniciarPartida.i: FortuneAvenueDev/src/menu/IniciarPartida.cpp.i
.PHONY : FortuneAvenueDev/src/menu/IniciarPartida.i

# target to preprocess a source file
FortuneAvenueDev/src/menu/IniciarPartida.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/IniciarPartida.cpp.i
.PHONY : FortuneAvenueDev/src/menu/IniciarPartida.cpp.i

FortuneAvenueDev/src/menu/IniciarPartida.s: FortuneAvenueDev/src/menu/IniciarPartida.cpp.s
.PHONY : FortuneAvenueDev/src/menu/IniciarPartida.s

# target to generate assembly for a file
FortuneAvenueDev/src/menu/IniciarPartida.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/IniciarPartida.cpp.s
.PHONY : FortuneAvenueDev/src/menu/IniciarPartida.cpp.s

FortuneAvenueDev/src/menu/menuP.o: FortuneAvenueDev/src/menu/menuP.cpp.o
.PHONY : FortuneAvenueDev/src/menu/menuP.o

# target to build an object file
FortuneAvenueDev/src/menu/menuP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/menuP.cpp.o
.PHONY : FortuneAvenueDev/src/menu/menuP.cpp.o

FortuneAvenueDev/src/menu/menuP.i: FortuneAvenueDev/src/menu/menuP.cpp.i
.PHONY : FortuneAvenueDev/src/menu/menuP.i

# target to preprocess a source file
FortuneAvenueDev/src/menu/menuP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/menuP.cpp.i
.PHONY : FortuneAvenueDev/src/menu/menuP.cpp.i

FortuneAvenueDev/src/menu/menuP.s: FortuneAvenueDev/src/menu/menuP.cpp.s
.PHONY : FortuneAvenueDev/src/menu/menuP.s

# target to generate assembly for a file
FortuneAvenueDev/src/menu/menuP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/menu/menuP.cpp.s
.PHONY : FortuneAvenueDev/src/menu/menuP.cpp.s

FortuneAvenueDev/src/network/Client.o: FortuneAvenueDev/src/network/Client.cpp.o
.PHONY : FortuneAvenueDev/src/network/Client.o

# target to build an object file
FortuneAvenueDev/src/network/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/Client.cpp.o
.PHONY : FortuneAvenueDev/src/network/Client.cpp.o

FortuneAvenueDev/src/network/Client.i: FortuneAvenueDev/src/network/Client.cpp.i
.PHONY : FortuneAvenueDev/src/network/Client.i

# target to preprocess a source file
FortuneAvenueDev/src/network/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/Client.cpp.i
.PHONY : FortuneAvenueDev/src/network/Client.cpp.i

FortuneAvenueDev/src/network/Client.s: FortuneAvenueDev/src/network/Client.cpp.s
.PHONY : FortuneAvenueDev/src/network/Client.s

# target to generate assembly for a file
FortuneAvenueDev/src/network/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/Client.cpp.s
.PHONY : FortuneAvenueDev/src/network/Client.cpp.s

FortuneAvenueDev/src/network/ClientData.o: FortuneAvenueDev/src/network/ClientData.cpp.o
.PHONY : FortuneAvenueDev/src/network/ClientData.o

# target to build an object file
FortuneAvenueDev/src/network/ClientData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/ClientData.cpp.o
.PHONY : FortuneAvenueDev/src/network/ClientData.cpp.o

FortuneAvenueDev/src/network/ClientData.i: FortuneAvenueDev/src/network/ClientData.cpp.i
.PHONY : FortuneAvenueDev/src/network/ClientData.i

# target to preprocess a source file
FortuneAvenueDev/src/network/ClientData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/ClientData.cpp.i
.PHONY : FortuneAvenueDev/src/network/ClientData.cpp.i

FortuneAvenueDev/src/network/ClientData.s: FortuneAvenueDev/src/network/ClientData.cpp.s
.PHONY : FortuneAvenueDev/src/network/ClientData.s

# target to generate assembly for a file
FortuneAvenueDev/src/network/ClientData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/ClientData.cpp.s
.PHONY : FortuneAvenueDev/src/network/ClientData.cpp.s

FortuneAvenueDev/src/network/NetworkMessage.o: FortuneAvenueDev/src/network/NetworkMessage.cpp.o
.PHONY : FortuneAvenueDev/src/network/NetworkMessage.o

# target to build an object file
FortuneAvenueDev/src/network/NetworkMessage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/NetworkMessage.cpp.o
.PHONY : FortuneAvenueDev/src/network/NetworkMessage.cpp.o

FortuneAvenueDev/src/network/NetworkMessage.i: FortuneAvenueDev/src/network/NetworkMessage.cpp.i
.PHONY : FortuneAvenueDev/src/network/NetworkMessage.i

# target to preprocess a source file
FortuneAvenueDev/src/network/NetworkMessage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/NetworkMessage.cpp.i
.PHONY : FortuneAvenueDev/src/network/NetworkMessage.cpp.i

FortuneAvenueDev/src/network/NetworkMessage.s: FortuneAvenueDev/src/network/NetworkMessage.cpp.s
.PHONY : FortuneAvenueDev/src/network/NetworkMessage.s

# target to generate assembly for a file
FortuneAvenueDev/src/network/NetworkMessage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/NetworkMessage.cpp.s
.PHONY : FortuneAvenueDev/src/network/NetworkMessage.cpp.s

FortuneAvenueDev/src/network/ServerMessageHandler.o: FortuneAvenueDev/src/network/ServerMessageHandler.cpp.o
.PHONY : FortuneAvenueDev/src/network/ServerMessageHandler.o

# target to build an object file
FortuneAvenueDev/src/network/ServerMessageHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/ServerMessageHandler.cpp.o
.PHONY : FortuneAvenueDev/src/network/ServerMessageHandler.cpp.o

FortuneAvenueDev/src/network/ServerMessageHandler.i: FortuneAvenueDev/src/network/ServerMessageHandler.cpp.i
.PHONY : FortuneAvenueDev/src/network/ServerMessageHandler.i

# target to preprocess a source file
FortuneAvenueDev/src/network/ServerMessageHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/ServerMessageHandler.cpp.i
.PHONY : FortuneAvenueDev/src/network/ServerMessageHandler.cpp.i

FortuneAvenueDev/src/network/ServerMessageHandler.s: FortuneAvenueDev/src/network/ServerMessageHandler.cpp.s
.PHONY : FortuneAvenueDev/src/network/ServerMessageHandler.s

# target to generate assembly for a file
FortuneAvenueDev/src/network/ServerMessageHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/network/ServerMessageHandler.cpp.s
.PHONY : FortuneAvenueDev/src/network/ServerMessageHandler.cpp.s

FortuneAvenueDev/src/settings/SettingsManager.o: FortuneAvenueDev/src/settings/SettingsManager.cpp.o
.PHONY : FortuneAvenueDev/src/settings/SettingsManager.o

# target to build an object file
FortuneAvenueDev/src/settings/SettingsManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/settings/SettingsManager.cpp.o
.PHONY : FortuneAvenueDev/src/settings/SettingsManager.cpp.o

FortuneAvenueDev/src/settings/SettingsManager.i: FortuneAvenueDev/src/settings/SettingsManager.cpp.i
.PHONY : FortuneAvenueDev/src/settings/SettingsManager.i

# target to preprocess a source file
FortuneAvenueDev/src/settings/SettingsManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/settings/SettingsManager.cpp.i
.PHONY : FortuneAvenueDev/src/settings/SettingsManager.cpp.i

FortuneAvenueDev/src/settings/SettingsManager.s: FortuneAvenueDev/src/settings/SettingsManager.cpp.s
.PHONY : FortuneAvenueDev/src/settings/SettingsManager.s

# target to generate assembly for a file
FortuneAvenueDev/src/settings/SettingsManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/settings/SettingsManager.cpp.s
.PHONY : FortuneAvenueDev/src/settings/SettingsManager.cpp.s

FortuneAvenueDev/src/ui/ButtonG.o: FortuneAvenueDev/src/ui/ButtonG.cpp.o
.PHONY : FortuneAvenueDev/src/ui/ButtonG.o

# target to build an object file
FortuneAvenueDev/src/ui/ButtonG.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/ButtonG.cpp.o
.PHONY : FortuneAvenueDev/src/ui/ButtonG.cpp.o

FortuneAvenueDev/src/ui/ButtonG.i: FortuneAvenueDev/src/ui/ButtonG.cpp.i
.PHONY : FortuneAvenueDev/src/ui/ButtonG.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/ButtonG.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/ButtonG.cpp.i
.PHONY : FortuneAvenueDev/src/ui/ButtonG.cpp.i

FortuneAvenueDev/src/ui/ButtonG.s: FortuneAvenueDev/src/ui/ButtonG.cpp.s
.PHONY : FortuneAvenueDev/src/ui/ButtonG.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/ButtonG.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/ButtonG.cpp.s
.PHONY : FortuneAvenueDev/src/ui/ButtonG.cpp.s

FortuneAvenueDev/src/ui/Cube.o: FortuneAvenueDev/src/ui/Cube.cpp.o
.PHONY : FortuneAvenueDev/src/ui/Cube.o

# target to build an object file
FortuneAvenueDev/src/ui/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Cube.cpp.o
.PHONY : FortuneAvenueDev/src/ui/Cube.cpp.o

FortuneAvenueDev/src/ui/Cube.i: FortuneAvenueDev/src/ui/Cube.cpp.i
.PHONY : FortuneAvenueDev/src/ui/Cube.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Cube.cpp.i
.PHONY : FortuneAvenueDev/src/ui/Cube.cpp.i

FortuneAvenueDev/src/ui/Cube.s: FortuneAvenueDev/src/ui/Cube.cpp.s
.PHONY : FortuneAvenueDev/src/ui/Cube.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Cube.cpp.s
.PHONY : FortuneAvenueDev/src/ui/Cube.cpp.s

FortuneAvenueDev/src/ui/MensageBox.o: FortuneAvenueDev/src/ui/MensageBox.cpp.o
.PHONY : FortuneAvenueDev/src/ui/MensageBox.o

# target to build an object file
FortuneAvenueDev/src/ui/MensageBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/MensageBox.cpp.o
.PHONY : FortuneAvenueDev/src/ui/MensageBox.cpp.o

FortuneAvenueDev/src/ui/MensageBox.i: FortuneAvenueDev/src/ui/MensageBox.cpp.i
.PHONY : FortuneAvenueDev/src/ui/MensageBox.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/MensageBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/MensageBox.cpp.i
.PHONY : FortuneAvenueDev/src/ui/MensageBox.cpp.i

FortuneAvenueDev/src/ui/MensageBox.s: FortuneAvenueDev/src/ui/MensageBox.cpp.s
.PHONY : FortuneAvenueDev/src/ui/MensageBox.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/MensageBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/MensageBox.cpp.s
.PHONY : FortuneAvenueDev/src/ui/MensageBox.cpp.s

FortuneAvenueDev/src/ui/ResourceGeneral.o: FortuneAvenueDev/src/ui/ResourceGeneral.cpp.o
.PHONY : FortuneAvenueDev/src/ui/ResourceGeneral.o

# target to build an object file
FortuneAvenueDev/src/ui/ResourceGeneral.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/ResourceGeneral.cpp.o
.PHONY : FortuneAvenueDev/src/ui/ResourceGeneral.cpp.o

FortuneAvenueDev/src/ui/ResourceGeneral.i: FortuneAvenueDev/src/ui/ResourceGeneral.cpp.i
.PHONY : FortuneAvenueDev/src/ui/ResourceGeneral.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/ResourceGeneral.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/ResourceGeneral.cpp.i
.PHONY : FortuneAvenueDev/src/ui/ResourceGeneral.cpp.i

FortuneAvenueDev/src/ui/ResourceGeneral.s: FortuneAvenueDev/src/ui/ResourceGeneral.cpp.s
.PHONY : FortuneAvenueDev/src/ui/ResourceGeneral.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/ResourceGeneral.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/ResourceGeneral.cpp.s
.PHONY : FortuneAvenueDev/src/ui/ResourceGeneral.cpp.s

FortuneAvenueDev/src/ui/Scrollbar.o: FortuneAvenueDev/src/ui/Scrollbar.cpp.o
.PHONY : FortuneAvenueDev/src/ui/Scrollbar.o

# target to build an object file
FortuneAvenueDev/src/ui/Scrollbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Scrollbar.cpp.o
.PHONY : FortuneAvenueDev/src/ui/Scrollbar.cpp.o

FortuneAvenueDev/src/ui/Scrollbar.i: FortuneAvenueDev/src/ui/Scrollbar.cpp.i
.PHONY : FortuneAvenueDev/src/ui/Scrollbar.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/Scrollbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Scrollbar.cpp.i
.PHONY : FortuneAvenueDev/src/ui/Scrollbar.cpp.i

FortuneAvenueDev/src/ui/Scrollbar.s: FortuneAvenueDev/src/ui/Scrollbar.cpp.s
.PHONY : FortuneAvenueDev/src/ui/Scrollbar.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/Scrollbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Scrollbar.cpp.s
.PHONY : FortuneAvenueDev/src/ui/Scrollbar.cpp.s

FortuneAvenueDev/src/ui/Sound.o: FortuneAvenueDev/src/ui/Sound.cpp.o
.PHONY : FortuneAvenueDev/src/ui/Sound.o

# target to build an object file
FortuneAvenueDev/src/ui/Sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Sound.cpp.o
.PHONY : FortuneAvenueDev/src/ui/Sound.cpp.o

FortuneAvenueDev/src/ui/Sound.i: FortuneAvenueDev/src/ui/Sound.cpp.i
.PHONY : FortuneAvenueDev/src/ui/Sound.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Sound.cpp.i
.PHONY : FortuneAvenueDev/src/ui/Sound.cpp.i

FortuneAvenueDev/src/ui/Sound.s: FortuneAvenueDev/src/ui/Sound.cpp.s
.PHONY : FortuneAvenueDev/src/ui/Sound.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/Sound.cpp.s
.PHONY : FortuneAvenueDev/src/ui/Sound.cpp.s

FortuneAvenueDev/src/ui/TextBox.o: FortuneAvenueDev/src/ui/TextBox.cpp.o
.PHONY : FortuneAvenueDev/src/ui/TextBox.o

# target to build an object file
FortuneAvenueDev/src/ui/TextBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/TextBox.cpp.o
.PHONY : FortuneAvenueDev/src/ui/TextBox.cpp.o

FortuneAvenueDev/src/ui/TextBox.i: FortuneAvenueDev/src/ui/TextBox.cpp.i
.PHONY : FortuneAvenueDev/src/ui/TextBox.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/TextBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/TextBox.cpp.i
.PHONY : FortuneAvenueDev/src/ui/TextBox.cpp.i

FortuneAvenueDev/src/ui/TextBox.s: FortuneAvenueDev/src/ui/TextBox.cpp.s
.PHONY : FortuneAvenueDev/src/ui/TextBox.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/TextBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/TextBox.cpp.s
.PHONY : FortuneAvenueDev/src/ui/TextBox.cpp.s

FortuneAvenueDev/src/ui/cell.o: FortuneAvenueDev/src/ui/cell.cpp.o
.PHONY : FortuneAvenueDev/src/ui/cell.o

# target to build an object file
FortuneAvenueDev/src/ui/cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/cell.cpp.o
.PHONY : FortuneAvenueDev/src/ui/cell.cpp.o

FortuneAvenueDev/src/ui/cell.i: FortuneAvenueDev/src/ui/cell.cpp.i
.PHONY : FortuneAvenueDev/src/ui/cell.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/cell.cpp.i
.PHONY : FortuneAvenueDev/src/ui/cell.cpp.i

FortuneAvenueDev/src/ui/cell.s: FortuneAvenueDev/src/ui/cell.cpp.s
.PHONY : FortuneAvenueDev/src/ui/cell.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/cell.cpp.s
.PHONY : FortuneAvenueDev/src/ui/cell.cpp.s

FortuneAvenueDev/src/ui/fileio.o: FortuneAvenueDev/src/ui/fileio.cpp.o
.PHONY : FortuneAvenueDev/src/ui/fileio.o

# target to build an object file
FortuneAvenueDev/src/ui/fileio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/fileio.cpp.o
.PHONY : FortuneAvenueDev/src/ui/fileio.cpp.o

FortuneAvenueDev/src/ui/fileio.i: FortuneAvenueDev/src/ui/fileio.cpp.i
.PHONY : FortuneAvenueDev/src/ui/fileio.i

# target to preprocess a source file
FortuneAvenueDev/src/ui/fileio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/fileio.cpp.i
.PHONY : FortuneAvenueDev/src/ui/fileio.cpp.i

FortuneAvenueDev/src/ui/fileio.s: FortuneAvenueDev/src/ui/fileio.cpp.s
.PHONY : FortuneAvenueDev/src/ui/fileio.s

# target to generate assembly for a file
FortuneAvenueDev/src/ui/fileio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fortuneAvenue.dir/build.make CMakeFiles/fortuneAvenue.dir/FortuneAvenueDev/src/ui/fileio.cpp.s
.PHONY : FortuneAvenueDev/src/ui/fileio.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fortuneAvenue"
	@echo "... FortuneAvenueDev/src/cinematic/Cinematic.o"
	@echo "... FortuneAvenueDev/src/cinematic/Cinematic.i"
	@echo "... FortuneAvenueDev/src/cinematic/Cinematic.s"
	@echo "... FortuneAvenueDev/src/core/ObjetosGlobal.o"
	@echo "... FortuneAvenueDev/src/core/ObjetosGlobal.i"
	@echo "... FortuneAvenueDev/src/core/ObjetosGlobal.s"
	@echo "... FortuneAvenueDev/src/core/ResourceGlobal.o"
	@echo "... FortuneAvenueDev/src/core/ResourceGlobal.i"
	@echo "... FortuneAvenueDev/src/core/ResourceGlobal.s"
	@echo "... FortuneAvenueDev/src/game/offiline/Bot.o"
	@echo "... FortuneAvenueDev/src/game/offiline/Bot.i"
	@echo "... FortuneAvenueDev/src/game/offiline/Bot.s"
	@echo "... FortuneAvenueDev/src/game/offiline/GameEndO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/GameEndO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/GameEndO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/GameManager.o"
	@echo "... FortuneAvenueDev/src/game/offiline/GameManager.i"
	@echo "... FortuneAvenueDev/src/game/offiline/GameManager.s"
	@echo "... FortuneAvenueDev/src/game/offiline/GameOfflineO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/GameOfflineO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/GameOfflineO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/GameOptionsO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/GameOptionsO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/GameOptionsO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/HouseBuyO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/HouseBuyO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/HouseBuyO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/MovePiecesO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/MovePiecesO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/MovePiecesO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/PieceSelectorO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/PieceSelectorO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/PieceSelectorO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/ResourceGameO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/ResourceGameO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/ResourceGameO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/RuletaO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/RuletaO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/RuletaO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/StealplayerO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/StealplayerO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/StealplayerO.s"
	@echo "... FortuneAvenueDev/src/game/offiline/nuloO.o"
	@echo "... FortuneAvenueDev/src/game/offiline/nuloO.i"
	@echo "... FortuneAvenueDev/src/game/offiline/nuloO.s"
	@echo "... FortuneAvenueDev/src/game/online/Chat.o"
	@echo "... FortuneAvenueDev/src/game/online/Chat.i"
	@echo "... FortuneAvenueDev/src/game/online/Chat.s"
	@echo "... FortuneAvenueDev/src/game/online/GameEnd.o"
	@echo "... FortuneAvenueDev/src/game/online/GameEnd.i"
	@echo "... FortuneAvenueDev/src/game/online/GameEnd.s"
	@echo "... FortuneAvenueDev/src/game/online/HouseBuy.o"
	@echo "... FortuneAvenueDev/src/game/online/HouseBuy.i"
	@echo "... FortuneAvenueDev/src/game/online/HouseBuy.s"
	@echo "... FortuneAvenueDev/src/game/online/MovePieces.o"
	@echo "... FortuneAvenueDev/src/game/online/MovePieces.i"
	@echo "... FortuneAvenueDev/src/game/online/MovePieces.s"
	@echo "... FortuneAvenueDev/src/game/online/MultiplayerGame.o"
	@echo "... FortuneAvenueDev/src/game/online/MultiplayerGame.i"
	@echo "... FortuneAvenueDev/src/game/online/MultiplayerGame.s"
	@echo "... FortuneAvenueDev/src/game/online/OnlineVars.o"
	@echo "... FortuneAvenueDev/src/game/online/OnlineVars.i"
	@echo "... FortuneAvenueDev/src/game/online/OnlineVars.s"
	@echo "... FortuneAvenueDev/src/game/online/PieceSelector.o"
	@echo "... FortuneAvenueDev/src/game/online/PieceSelector.i"
	@echo "... FortuneAvenueDev/src/game/online/PieceSelector.s"
	@echo "... FortuneAvenueDev/src/game/online/ResourceGame.o"
	@echo "... FortuneAvenueDev/src/game/online/ResourceGame.i"
	@echo "... FortuneAvenueDev/src/game/online/ResourceGame.s"
	@echo "... FortuneAvenueDev/src/game/online/Ruleta.o"
	@echo "... FortuneAvenueDev/src/game/online/Ruleta.i"
	@echo "... FortuneAvenueDev/src/game/online/Ruleta.s"
	@echo "... FortuneAvenueDev/src/game/online/Stealplayer.o"
	@echo "... FortuneAvenueDev/src/game/online/Stealplayer.i"
	@echo "... FortuneAvenueDev/src/game/online/Stealplayer.s"
	@echo "... FortuneAvenueDev/src/game/online/loading.o"
	@echo "... FortuneAvenueDev/src/game/online/loading.i"
	@echo "... FortuneAvenueDev/src/game/online/loading.s"
	@echo "... FortuneAvenueDev/src/game/online/nulo.o"
	@echo "... FortuneAvenueDev/src/game/online/nulo.i"
	@echo "... FortuneAvenueDev/src/game/online/nulo.s"
	@echo "... FortuneAvenueDev/src/main.o"
	@echo "... FortuneAvenueDev/src/main.i"
	@echo "... FortuneAvenueDev/src/main.s"
	@echo "... FortuneAvenueDev/src/menu/GameModeSelector.o"
	@echo "... FortuneAvenueDev/src/menu/GameModeSelector.i"
	@echo "... FortuneAvenueDev/src/menu/GameModeSelector.s"
	@echo "... FortuneAvenueDev/src/menu/IniciaUser.o"
	@echo "... FortuneAvenueDev/src/menu/IniciaUser.i"
	@echo "... FortuneAvenueDev/src/menu/IniciaUser.s"
	@echo "... FortuneAvenueDev/src/menu/IniciarPartida.o"
	@echo "... FortuneAvenueDev/src/menu/IniciarPartida.i"
	@echo "... FortuneAvenueDev/src/menu/IniciarPartida.s"
	@echo "... FortuneAvenueDev/src/menu/menuP.o"
	@echo "... FortuneAvenueDev/src/menu/menuP.i"
	@echo "... FortuneAvenueDev/src/menu/menuP.s"
	@echo "... FortuneAvenueDev/src/network/Client.o"
	@echo "... FortuneAvenueDev/src/network/Client.i"
	@echo "... FortuneAvenueDev/src/network/Client.s"
	@echo "... FortuneAvenueDev/src/network/ClientData.o"
	@echo "... FortuneAvenueDev/src/network/ClientData.i"
	@echo "... FortuneAvenueDev/src/network/ClientData.s"
	@echo "... FortuneAvenueDev/src/network/NetworkMessage.o"
	@echo "... FortuneAvenueDev/src/network/NetworkMessage.i"
	@echo "... FortuneAvenueDev/src/network/NetworkMessage.s"
	@echo "... FortuneAvenueDev/src/network/ServerMessageHandler.o"
	@echo "... FortuneAvenueDev/src/network/ServerMessageHandler.i"
	@echo "... FortuneAvenueDev/src/network/ServerMessageHandler.s"
	@echo "... FortuneAvenueDev/src/settings/SettingsManager.o"
	@echo "... FortuneAvenueDev/src/settings/SettingsManager.i"
	@echo "... FortuneAvenueDev/src/settings/SettingsManager.s"
	@echo "... FortuneAvenueDev/src/ui/ButtonG.o"
	@echo "... FortuneAvenueDev/src/ui/ButtonG.i"
	@echo "... FortuneAvenueDev/src/ui/ButtonG.s"
	@echo "... FortuneAvenueDev/src/ui/Cube.o"
	@echo "... FortuneAvenueDev/src/ui/Cube.i"
	@echo "... FortuneAvenueDev/src/ui/Cube.s"
	@echo "... FortuneAvenueDev/src/ui/MensageBox.o"
	@echo "... FortuneAvenueDev/src/ui/MensageBox.i"
	@echo "... FortuneAvenueDev/src/ui/MensageBox.s"
	@echo "... FortuneAvenueDev/src/ui/ResourceGeneral.o"
	@echo "... FortuneAvenueDev/src/ui/ResourceGeneral.i"
	@echo "... FortuneAvenueDev/src/ui/ResourceGeneral.s"
	@echo "... FortuneAvenueDev/src/ui/Scrollbar.o"
	@echo "... FortuneAvenueDev/src/ui/Scrollbar.i"
	@echo "... FortuneAvenueDev/src/ui/Scrollbar.s"
	@echo "... FortuneAvenueDev/src/ui/Sound.o"
	@echo "... FortuneAvenueDev/src/ui/Sound.i"
	@echo "... FortuneAvenueDev/src/ui/Sound.s"
	@echo "... FortuneAvenueDev/src/ui/TextBox.o"
	@echo "... FortuneAvenueDev/src/ui/TextBox.i"
	@echo "... FortuneAvenueDev/src/ui/TextBox.s"
	@echo "... FortuneAvenueDev/src/ui/cell.o"
	@echo "... FortuneAvenueDev/src/ui/cell.i"
	@echo "... FortuneAvenueDev/src/ui/cell.s"
	@echo "... FortuneAvenueDev/src/ui/fileio.o"
	@echo "... FortuneAvenueDev/src/ui/fileio.i"
	@echo "... FortuneAvenueDev/src/ui/fileio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

